(this["webpackJsonpreact-firebase-semantic-ui-template"] = this["webpackJsonpreact-firebase-semantic-ui-template"] || []).push([[0],{

/***/ "./src/constants/translation.js":
/*!**************************************!*\
  !*** ./src/constants/translation.js ***!
  \**************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* WEBPACK VAR INJECTION */(function(__react_refresh_utils__, __react_refresh_error_overlay__) {__webpack_require__.$Refresh$.runtime = __webpack_require__(/*! ./node_modules/react-refresh/runtime.js */ "./node_modules/react-refresh/runtime.js");
__webpack_require__.$Refresh$.setup(module.i);

const TRANSLATIONS = {
  EN: {
    GLOBAL: {
      ariaDark: "Toggle Dark Mode"
    },
    HOME: {
      header: "Coming Soon!",
      report1: "Report 1: Delivery Revenue",
      report2: "Report 2: Pickup Revenue",
      report3: "Report 3: Total by Carrier Revenue",
      report4: "Report 4: Delivery Routific",
      report5: "Report 5: Driver Routific",
      report6: "Report 6: Items Routific",
      report7: "Report 7: Production Global",
      report8: "Report 8: Production Total",
      report9: "Report 9: Production Pickup",
      report10: "Report 10: Production Delivery",
      report11: "Report 11: Order Accounting",
      report12: "Report 12: Delivery Zones Tickets",
      report13: "Report 13: Pickup Point Tickets",
      report1Description: `Shows all the orders in delivery along a period of time, in a given delivery zone in CSV format.`,
      report2Description: `Shows all the orders in pickup along on a period of time, at a given pickup point in CSV format.`,
      report3Description: `Shows the number of orders and total revenue by carrier in CSV format.`,
      report4Description: `Shows the order information in CSV format.`,
      report5Description: `Generated by Routific.`,
      report6Description: `Show the total number of items each driver must bring on his route on a given date, in a given zone in PDF format.`,
      report7Description: `Shows the number of items in pickup + delivery on a given date as well as the total in PDF format.`,
      report8Description: `Shows the total number of items in pickup + delivery on a given date in PDF format.`,
      report9Description: `Shows the number of items in pickup on a given date as well as the total of this item, at a given point of sale in CSV format.`,
      report10Description: `Shows the number of items in delivery on a given date as well as the total of this item, in a given delivery zone in PDF format.`,
      report11Description: `Shows total items sold on a given date in CSV format.`,
      report12Description: `Generates all the delivery tickets of a given date in a given delivery zone upon delivery in PDF format.`,
      report13Description: `Generates all the delivery tickets of a given date at a given pickup point upon order pickup in PDF format.`
    },
    NAVIGATION: {
      header: "header",
      imageAlt: "Logo",
      home: "Home",
      reports: "Reports",
      account: "Account",
      admin: "Admin",
      signIn: "Sign In",
      signUp: "Sign Up",
      signOut: "Sign Out",
      forgotPassword: "Forgot Password?",
      ariaLanguage: "Change Language"
    },
    FOOTER: {
      support: "Support",
      phone: "+1 (866) 123-4567",
      phoneTitle: "Call Support 1 (866) 123-4567",
      helpCenter: "Help Center",
      mail: "help@milesbd.ca",
      mailTitle: "email help@milesbd.ca",
      mailHref: "mailto:help@milesbd.ca?subject=Question about Firebase/React/Semantic UI template site",
      company: "Company",
      about: "About Us",
      location: "Our Location",
      blog: "Our Blog",
      events: "Our Events",
      h3: "Company Tagline",
      subheader: "We offer complex business solutions to keep you on the bleeding edge of technology. We can provide you with consultation that will help grow your audience and profits.",
      facebook: "Connect with us on Facebook",
      instagram: "Connect with us on Instagram",
      twitter: "Connect with us on Twitter",
      github: "View our projects on GitHub",
      copyCompany: "Your Company"
    },
    ACCOUNT: {
      heading: "Account Settings",
      subHeading: "Manage your account details",
      welcome: "Welcome ",
      memberSince: "Member since ",
      yourInfo: "Your Info",
      signInMethods: "Sign In Methods",
      deactivate: "Deactivate ",
      link: "Link ",
      updateInfoButton: "Update my Info",
      updatePassword: "Update Password",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmNewPassword: "Confirm New Password",
      infoHeader: "Your Account is connected using Google",
      infoMessage: "Password Updates for accounts connected through Google must be done in your Google Account"
    },
    SIGNUP: {
      header: "Sign up for an account",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email Address",
      phone: "Phone Number",
      passwordOne: "Password",
      passwordTwo: "Confirm Password",
      signUp: "Sign Up",
      or: "OR",
      google: "Connect with Google",
      message: "Don't have an account? "
    },
    SIGNIN: {
      header: "Sign In",
      email: "Email Address",
      password: "Password",
      or: "OR"
    }
  },
  FR: {
    GLOBAL: {
      ariaDark: "Basculer mode nuit"
    },
    HOME: {
      header: "Site web bientôt disponible !",
      report1: "Rapport 1",
      report2: "Rapport 2",
      report3: "Rapport 3",
      report4: "Rapport 4",
      report5: "Rapport 5",
      report6: "Rapport 6",
      report7: "Rapport 7",
      report8: "Rapport 8",
      report9: "Rapport 9",
      report10: "Rapport 10",
      report11: "Rapport 11",
      report12: "Rapport 12",
      report13: "Rapport 13",
      report1Description: `Shows all the orders in delivery along a period of time, in a given delivery zone in CSV format.`,
      report2Description: `Shows all the orders in pickup along on a period of time, at a given pickup point in CSV format.`,
      report3Description: `Shows the number of orders and total revenue by carrier in CSV format.`,
      report4Description: `Shows the order information in CSV format.`,
      report5Description: `Generated by Routific.`,
      report6Description: `Show the total number of items each driver must bring on his route on a given date, in a given zone in PDF format.`,
      report7Description: `Shows the number of items in pickup + delivery on a given date as well as the total in PDF format.`,
      report8Description: `Shows the total number of items in pickup + delivery on a given date in PDF format.`,
      report9Description: `Shows the number of items in pickup on a given date as well as the total of this item, at a given point of sale in CSV format.`,
      report10Description: `Shows the number of items in delivery on a given date as well as the total of this item, in a given delivery zone in PDF format.`,
      report11Description: `Shows total items sold on a given date in CSV format.`,
      report12Description: `Generates all the delivery tickets of a given date in a given delivery zone upon delivery in PDF format.`,
      report13Description: `Generates all the delivery tickets of a given date at a given pickup point upon order pickup in PDF format.`
    },
    NAVIGATION: {
      header: "header",
      imageAlt: "Logo",
      home: "Acceuil",
      reports: "Rapports",
      account: "Compte",
      admin: "Admin",
      signIn: "Connexion",
      signUp: "S'inscrire",
      signOut: "Deconnexion",
      forgotPassword: "Mot de passe oublié ?",
      ariaLanguage: "Choisissez la langue"
    },
    FOOTER: {
      support: "Soutien",
      phone: "+1 (866) 123-4567",
      phoneTitle: "Nous rejoindre au 1 (866) 123-4567",
      helpCenter: "Center d'aide",
      mail: "help@milesbd.ca",
      mailTitle: "Envoyer un courriel à help@milesbd.ca",
      mailHref: "mailto:help@milesbd.ca?subject=Question à propos du site template Firebase/React/Semantic UI",
      company: "Entreprise",
      about: "À Propos",
      location: "Nos Locations",
      blog: "Notre Blogue",
      events: "Nos Événements",
      h3: "Mots de l'entreprise",
      subheader: "Nous proposons des solutions commerciales complexes pour vous permettre de rester à la pointe de la technologie. Nous pouvons vous fournir des conseils qui vous aideront à étendre votre influence public et vos profits.",
      facebook: "Suivez-nous sur Facebook",
      instagram: "Suivez-nous sur Instagram",
      twitter: "Suivez-nous sur Twitter",
      github: "Consultez nos projets sur GitHub",
      copyCompany: "Votre Entreprise"
    },
    ACCOUNT: {
      heading: "Paramètres du compte",
      subHeading: "Gérer les détails de votre compte",
      welcome: "Bienvenue ",
      memberSince: "Membre depuis ",
      yourInfo: "Vos informations",
      signInMethods: "Méthodes de connexion",
      deactivate: "Désactiver ",
      link: "Relier ",
      updateInfoButton: "Mettre à jour mes informations",
      updatePassword: "Mettre à jour le mot de passe",
      currentPassword: "Mot de passe courante",
      newPassword: "Nouveau mot de passe",
      confirmNewPassword: "Confirmer Nouveau mot de passe",
      infoHeader: "Votre compte est connecté avec votre usager Google",
      infoMessage: "La mise à jour des mots de passe pour les comptes connectés via Google doit être effectuée dans votre compte Google."
    },
    SIGNUP: {
      header: "S'inscrire pour un compte",
      firstName: "Prénom",
      lastName: "Nom de famille",
      email: "Courriel",
      phone: "Numéro de téléphone",
      passwordOne: "Mot de passe",
      passwordTwo: "Confirm mot de passe",
      signUp: "S'inscrire",
      or: "OU",
      google: "Connectez-vous avec Google",
      message: "Vous n'avez pas de compte ? "
    },
    SIGNIN: {
      header: "Connexion",
      email: "Courriel",
      password: "Mot de passe",
      or: "OU"
    }
  }
};
/* harmony default export */ __webpack_exports__["default"] = (TRANSLATIONS);

const currentExports = __react_refresh_utils__.getModuleExports(module.i);
__react_refresh_utils__.registerExportsForReactRefresh(currentExports, module.i);

if (true) {
  const isHotUpdate = !!module.hot.data;
  const prevExports = isHotUpdate ? module.hot.data.prevExports : null;

  if (__react_refresh_utils__.isReactRefreshBoundary(currentExports)) {
    module.hot.dispose(
      /**
       * A callback to performs a full refresh if React has unrecoverable errors,
       * and also caches the to-be-disposed module.
       * @param {*} data A hot module data object from Webpack HMR.
       * @returns {void}
       */
      function hotDisposeCallback(data) {
        // We have to mutate the data object to get data registered and cached
        data.prevExports = currentExports;
      }
    );
    module.hot.accept(
      /**
       * An error handler to allow self-recovering behaviours.
       * @param {Error} error An error occurred during evaluation of a module.
       * @returns {void}
       */
      function hotErrorHandler(error) {
        if (
          typeof __react_refresh_error_overlay__ !== 'undefined' &&
          __react_refresh_error_overlay__
        ) {
          __react_refresh_error_overlay__.handleRuntimeError(error);
        }

        if (typeof __react_refresh_test__ !== 'undefined' && __react_refresh_test__) {
          if (window.onHotAcceptError) {
            window.onHotAcceptError(error.message);
          }
        }

        __webpack_require__.c[module.i].hot.accept(hotErrorHandler);
      }
    );

    if (isHotUpdate) {
      if (
        __react_refresh_utils__.isReactRefreshBoundary(prevExports) &&
        __react_refresh_utils__.shouldInvalidateReactRefreshBoundary(prevExports, currentExports)
      ) {
        module.hot.invalidate();
      } else {
        __react_refresh_utils__.enqueueUpdate(
          /**
           * A function to dismiss the error overlay after performing React refresh.
           * @returns {void}
           */
          function updateCallback() {
            if (
              typeof __react_refresh_error_overlay__ !== 'undefined' &&
              __react_refresh_error_overlay__
            ) {
              __react_refresh_error_overlay__.clearRuntimeErrors();
            }
          }
        );
      }
    }
  } else {
    if (isHotUpdate && __react_refresh_utils__.isReactRefreshBoundary(prevExports)) {
      module.hot.invalidate();
    }
  }
}
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshUtils.js */ "./node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshUtils.js"), __webpack_require__(/*! ./node_modules/react-dev-utils/refreshOverlayInterop.js */ "./node_modules/react-dev-utils/refreshOverlayInterop.js")))

/***/ })

}]);
//# sourceMappingURL=0.chunk.js.map